services:
  webserver:
    image: node:16
    environment:
      - PORT=8000
    ports:
      - '8000:8000'
    working_dir: /var/www/webserver
    volumes:
      - .:/var/www/webserver
    command: ['npm', 'run', 'watch:webserver']
volumes:
  db_data:
